In [2]:
import pandas as pd

In [3]:
df=pd.read_csv('houseprice.csv',usecols=["SalePrice", "MSSubClass", "MSZoning", "LotFrontage", "LotArea",
                                         "Street", "YearBuilt", "LotShape", "1stFlrSF", "2ndFlrSF"]).dropna()

In [4]:
df.shape  #1201 records ,10 Features

(1201, 10)

In [5]:
df.head() # salesprice is the depending feature here

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,YearBuilt,1stFlrSF,2ndFlrSF,SalePrice
0,60,RL,65.0,8450,Pave,Reg,2003,856,854,208500
1,20,RL,80.0,9600,Pave,Reg,1976,1262,0,181500
2,60,RL,68.0,11250,Pave,IR1,2001,920,866,223500
3,70,RL,60.0,9550,Pave,IR1,1915,961,756,140000
4,60,RL,84.0,14260,Pave,IR1,2000,1145,1053,250000

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MSSubClass   1201 non-null   int64
 1   MSZoning     1201 non-null   object
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64
 4   Street       1201 non-null   object
 5   LotShape     1201 non-null   object
 6   YearBuilt    1201 non-null   int64
 7   1stFlrSF     1201 non-null   int64
 8   2ndFlrSF     1201 non-null   int64
 9   SalePrice    1201 non-null   int64
dtypes: float64(1), int64(6), object(3)
memory usage: 103.2+ KB

In [10]:
for i in df.columns:
    print("Column name {} and unique values are {}".format(i,len(df[i].unique()))) #from all the columns I took Iam seeing how many unique values are present in each of my column
#from the below output MSSubclass,MS Zoning,Street and Lotshape are categorical

Column name MSSubClass and unique values are 15
Column name MSZoning and unique values are 5
Column name LotFrontage and unique values are 110
Column name LotArea and unique values are 869
Column name Street and unique values are 2
Column name LotShape and unique values are 4
Column name YearBuilt and unique values are 112
Column name 1stFlrSF and unique values are 678
Column name 2ndFlrSF and unique values are 368
Column name SalePrice and unique values are 597

In [11]:
import datetime
datetime.datetime.now().year

2024

In [14]:
df['Total Years']=datetime.datetime.now().year-df['YearBuilt'] #To replace the yearbuilt with total number of years

In [15]:
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,YearBuilt,1stFlrSF,2ndFlrSF,SalePrice,Total Years
0,60,RL,65.0,8450,Pave,Reg,2003,856,854,208500,21
1,20,RL,80.0,9600,Pave,Reg,1976,1262,0,181500,48
2,60,RL,68.0,11250,Pave,IR1,2001,920,866,223500,23
3,70,RL,60.0,9550,Pave,IR1,1915,961,756,140000,109
4,60,RL,84.0,14260,Pave,IR1,2000,1145,1053,250000,24

In [16]:
df.drop("YearBuilt",axis=1,inplace=True) #dropping the yearbuilt as we got total years now

In [87]:
df.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', '1stFlrSF', '2ndFlrSF', 'SalePrice', 'Total Years'],
      dtype='object')

In [20]:
cat_features=["MSSubClass", "MSZoning", "Street", "LotShape"]  #categorical features all the features other than this are continous features 
out_feature="SalePrice" #Output Feature

In [23]:
df["MSSubClass"].unique() #here in the below output I have all unique values in integer format I have to convert all this into categorical features
#to convert the unique integer values into categorical features I am using label encoding

array([ 60,  20,  70,  50, 190,  45,  90, 120,  30,  80, 160,  75, 180,
        40,  85], dtype=int64)

In [24]:
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
lbl_encoders["MSSubClass"]=LabelEncoder()
lbl_encoders["MSSubClass"].fit_transform(df["MSSubClass"])#after applying label encoding we can see that all the above unique values are indexed

array([5, 0, 5, ..., 6, 0, 0], dtype=int64)

In [25]:
lbl_encoders

{'MSSubClass': LabelEncoder()}

In [31]:
from sklearn.preprocessing import LabelEncoder
lbl_encoders={}
for feature in cat_features:
    lbl_encoders[feature]=LabelEncoder()
    df[feature]=lbl_encoders[feature].fit_transform(df[feature]) #here I applied label encoding to all my categorical features 
#The label encoding was done to do embedding ,to do embedding all the categorical features are need to be indexed

In [32]:
df #In the below dataset we can see all the categorical features are indexed

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,1stFlrSF,2ndFlrSF,SalePrice,Total Years
0,5,3,65.0,8450,1,3,856,854,208500,21
1,0,3,80.0,9600,1,3,1262,0,181500,48
2,5,3,68.0,11250,1,0,920,866,223500,23
3,6,3,60.0,9550,1,0,961,756,140000,109
4,5,3,84.0,14260,1,0,1145,1053,250000,24
...,...,...,...,...,...,...,...,...,...,...
1455,5,3,62.0,7917,1,3,953,694,175000,25
1456,0,3,85.0,13175,1,3,2073,0,210000,46
1457,6,3,66.0,9042,1,3,1188,1152,266500,83
1458,0,3,68.0,9717,1,3,1078,0,142125,74
1459,0,3,75.0,9937,1,3,1256,0,147500,59

In [37]:
### Stacking and Converting Into Tensors
import numpy as np
cat_features=np.stack([df['MSSubClass'],df['MSZoning'],df['Street'],df['LotShape']],1)
cat_features#Here I stacked all my categorical features as columns,the 1 in the above code represents that
#Iam doing this to convert all my categorical features by making them as an numpy array and after that  into tensors

array([[5, 3, 1, 3],
       [0, 3, 1, 3],
       [5, 3, 1, 0],
       ...,
       [6, 3, 1, 3],
       [0, 3, 1, 3],
       [0, 3, 1, 3]], dtype=int64)

In [42]:
### Convert numpy to Tensors
import torch
cat_features=torch.tensor(cat_features,dtype=torch.int64) 
cat_features

C:\Users\TEJ SAI PRANAV REDDY\AppData\Local\Temp\ipykernel_14976\1875173645.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  cat_features=torch.tensor(cat_features,dtype=torch.int64)

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [43]:
#### create continuous variable
cont_features=[]
for i in df.columns:
    if i in ["MSSubClass", "MSZoning", "Street", "LotShape","SalePrice"]:
        pass
    else:
        cont_features.append(i) #Here to consider all my continous features I implemented a for loop which excludes all categorical features

In [44]:
cont_features

['LotFrontage', 'LotArea', '1stFlrSF', '2ndFlrSF', 'Total Years']

In [49]:
### Stacking continuous variable to a tensor
cont_values=np.stack([df[i].values for i in cont_features],axis=1)
cont_values=torch.tensor(cont_values,dtype=torch.float) #all categorical features are specified with integer where as for continous it should be specified with float
cont_values #Above I stacked all the categorical features in the same way I stacked all the continous variables here. 
#And after that I converted all the numpy arrays into tensors

tensor([[   65.,  8450.,   856.,   854.,    21.],
        [   80.,  9600.,  1262.,     0.,    48.],
        [   68., 11250.,   920.,   866.,    23.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    83.],
        [   68.,  9717.,  1078.,     0.,    74.],
        [   75.,  9937.,  1256.,     0.,    59.]])

In [50]:
cont_values.dtype

torch.float32

In [51]:
### Dependent Feature 
y=torch.tensor(df['SalePrice'].values,dtype=torch.float).reshape(-1,1)
y#Here I converted the dependent feature as a tensor and I did reshape because we need a two dimensional array

tensor([[208500.],
        [181500.],
        [223500.],
        ...,
        [266500.],
        [142125.],
        [147500.]])

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1201 entries, 0 to 1459
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   MSSubClass   1201 non-null   int64
 1   MSZoning     1201 non-null   int64
 2   LotFrontage  1201 non-null   float64
 3   LotArea      1201 non-null   int64
 4   Street       1201 non-null   int64
 5   LotShape     1201 non-null   int64
 6   1stFlrSF     1201 non-null   int64
 7   2ndFlrSF     1201 non-null   int64
 8   SalePrice    1201 non-null   int64
 9   Total Years  1201 non-null   int64
dtypes: float64(1), int64(9)
memory usage: 103.2 KB

In [53]:
cat_features.shape,cont_values.shape,y.shape

(torch.Size([1201, 4]), torch.Size([1201, 5]), torch.Size([1201, 1]))

In [55]:
len(df['MSSubClass'].unique()) #Embedding starts from here 
#Embedding is only supposed to done for categorical features

15

In [56]:
#### Embedding Size For Categorical columns
cat_dims=[len(df[col].unique()) for col in ["MSSubClass", "MSZoning", "Street", "LotShape"]] #here Iam just checking how many unique values are present 
#In each categorical feature

In [60]:
cat_dims #In embedding the inputs are categorical features dimensions that is 15,5,2,4

[15, 5, 2, 4]

In [63]:
###output dimension should be setbased on input dimension(min(50,feature dimension/2))
embedding_dim= [(x, min(50, (x + 1) // 2)) for x in cat_dims]

In [67]:
embedding_dim #In the below code output we got is 8 that is calculated as min(15+1/2 =8 ) #These all are data preprocessing steps

[(15, 8), (5, 3), (2, 1), (4, 2)]

In [69]:

import torch
import torch.nn as nn
import torch.nn.functional as F
embed_representation=nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim]) #we use module list here because we have multiple dimensions 
embed_representation #here I just created a module list  to see what kind of vectors iam getting

ModuleList(
  (0): Embedding(15, 8)
  (1): Embedding(5, 3)
  (2): Embedding(2, 1)
  (3): Embedding(4, 2)
)

In [139]:
cat_features

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        ...,
        [6, 3, 1, 3],
        [0, 3, 1, 3],
        [0, 3, 1, 3]])

In [70]:
cat_featuresz=cat_features[:4]
cat_featuresz #iam doing embedding to only top four of my categorical features so I indexed it like that

tensor([[5, 3, 1, 3],
        [0, 3, 1, 3],
        [5, 3, 1, 0],
        [6, 3, 1, 0]])

In [71]:
pd.set_option('display.max_rows', 500)
embedding_val=[] #here I created a list 
for i,e in enumerate(embed_representation):
    embedding_val.append(e(cat_features[:,i])) #The module features I had I converted all of them into vectors

In [83]:
embedding_val#To understand the below output in clear if you take cat_features output the first column is 5,0,5,6 and the output is 8 dimensions
# so the embedding created 8 vectors

[tensor([[ 0.1642,  0.0829,  1.1666,  ...,  0.1243,  0.2881, -0.5378],
         [ 0.4815,  1.1371, -1.6158,  ...,  0.0414,  1.0021, -0.9634],
         [ 0.1642,  0.0829,  1.1666,  ...,  0.1243,  0.2881, -0.5378],
         ...,
         [ 0.8517,  0.4354, -0.8424,  ..., -0.1143,  1.2039, -1.6079],
         [ 0.4815,  1.1371, -1.6158,  ...,  0.0414,  1.0021, -0.9634],
         [ 0.4815,  1.1371, -1.6158,  ...,  0.0414,  1.0021, -0.9634]],
        grad_fn=<EmbeddingBackward0>),
 tensor([[-2.1012,  0.3745, -1.2470],
         [-2.1012,  0.3745, -1.2470],
         [-2.1012,  0.3745, -1.2470],
         ...,
         [-2.1012,  0.3745, -1.2470],
         [-2.1012,  0.3745, -1.2470],
         [-2.1012,  0.3745, -1.2470]], grad_fn=<EmbeddingBackward0>),
 tensor([[-0.9180],
         [-0.9180],
         [-0.9180],
         ...,
         [-0.9180],
         [-0.9180],
         [-0.9180]], grad_fn=<EmbeddingBackward0>),
 tensor([[ 1.5920, -0.6318],
         [ 1.5920, -0.6318],
         [-0.9684, -0.4804],
         ...,
         [ 1.5920, -0.6318],
         [ 1.5920, -0.6318],
         [ 1.5920, -0.6318]], grad_fn=<EmbeddingBackward0>)]

In [75]:
z = torch.cat(embedding_val, 1)
z#in the above output even if we get a proper output it was not stacked in a proper way to stack it in a proper way I concatenated here columnwise

tensor([[ 0.1642,  0.0829,  1.1666,  ..., -0.9180,  1.5920, -0.6318],
        [ 0.4815,  1.1371, -1.6158,  ..., -0.9180,  1.5920, -0.6318],
        [ 0.1642,  0.0829,  1.1666,  ..., -0.9180, -0.9684, -0.4804],
        ...,
        [ 0.8517,  0.4354, -0.8424,  ..., -0.9180,  1.5920, -0.6318],
        [ 0.4815,  1.1371, -1.6158,  ..., -0.9180,  1.5920, -0.6318],
        [ 0.4815,  1.1371, -1.6158,  ..., -0.9180,  1.5920, -0.6318]],
       grad_fn=<CatBackward0>)

In [76]:
#### Implement dropupout
droput=nn.Dropout(.4) #Iam using a droupout layer here to avoid overfitting

In [154]:
final_embed=droput(z)
final_embed

tensor([[ 0.0000, -3.9777, -1.8981,  ...,  1.2824,  0.0000, -0.0000],
        [ 1.0840,  0.0000,  0.0000,  ...,  1.2824,  0.0000, -1.7834],
        [ 1.1572, -3.9777, -1.8981,  ...,  0.0000, -0.0000, -0.0000],
        ...,
        [ 0.0000,  1.2390, -1.6782,  ...,  0.0000,  0.0000, -0.0000],
        [ 0.0000,  0.7187,  3.5020,  ...,  0.0000,  0.6231, -1.7834],
        [ 0.0000,  0.7187,  3.5020,  ...,  1.2824,  0.0000, -0.0000]],
       grad_fn=<MulBackward0>)

In [77]:
##### Create a Feed Forward Neural Network
import torch
import torch.nn as nn
import torch.nn.functional as F
class FeedForwardNN(nn.Module): # I defined my class here as feedforward neural network #I used nn.module because I can inherit the neural network 

    def __init__(self, embedding_dim, n_cont, out_sz, layers, p=0.5): #I had defined two functions here one is def and another is def forward and p is my dropout ratio.
        super().__init__() #we have to do this step to inherit all the parameters from nn.module
        self.embeds = nn.ModuleList([nn.Embedding(inp,out) for inp,out in embedding_dim])
        self.emb_drop = nn.Dropout(p)
        self.bn_cont = nn.BatchNorm1d(n_cont)
        
        layerlist = []
        n_emb = sum((out for inp,out in embedding_dim)) #number of embedding dimensions 
        n_in = n_emb + n_cont #number of inputs 
        
        for i in layers:
            layerlist.append(nn.Linear(n_in,i)) 
            layerlist.append(nn.ReLU(inplace=True))
            layerlist.append(nn.BatchNorm1d(i))
            layerlist.append(nn.Dropout(p))
            n_in = i
        layerlist.append(nn.Linear(layers[-1],out_sz))
            
        self.layers = nn.Sequential(*layerlist)
    
    def forward(self, x_cat, x_cont):
        embeddings = []
        for i,e in enumerate(self.embeds):
            embeddings.append(e(x_cat[:,i]))
        x = torch.cat(embeddings, 1)
        x = self.emb_drop(x)
        
        x_cont = self.bn_cont(x_cont)
        x = torch.cat([x, x_cont], 1)
        x = self.layers(x)
        return x

In [158]:
len(cont_features)

5

In [79]:
torch.manual_seed(100)
model=FeedForwardNN(embedding_dim,len(cont_features),1,[100,50],p=0.4)

In [80]:
model

FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)

In [82]:
loss_function=nn.MSELoss() #later I will convert this into RMSE
optimizer=torch.optim.Adam(model.parameters(),lr=0.01)

In [165]:
df.shape

(1201, 10)

In [167]:
cont_values

tensor([[   65.,  8450.,   856.,   854.,    21.],
        [   80.,  9600.,  1262.,     0.,    48.],
        [   68., 11250.,   920.,   866.,    23.],
        ...,
        [   66.,  9042.,  1188.,  1152.,    83.],
        [   68.,  9717.,  1078.,     0.,    74.],
        [   75.,  9937.,  1256.,     0.,    59.]])

In [169]:
cont_values.shape

torch.Size([1201, 5])

In [171]:
#Train_test_split
batch_size=1200
test_size=int(batch_size*0.15)
train_categorical=cat_features[:batch_size-test_size]
test_categorical=cat_features[batch_size-test_size:batch_size]
train_cont=cont_values[:batch_size-test_size]
test_cont=cont_values[batch_size-test_size:batch_size]
y_train=y[:batch_size-test_size]
y_test=y[batch_size-test_size:batch_size]

In [173]:
len(train_categorical),len(test_categorical),len(train_cont),len(test_cont),len(y_train),len(y_test)

(1020, 180, 1020, 180, 1020, 180)

In [175]:
epochs=5000
final_losses=[]
for i in range(epochs):
    i=i+1
    y_pred=model(train_categorical,train_cont)
    loss=torch.sqrt(loss_function(y_pred,y_train)) ### RMSE
    final_losses.append(loss)
    if i%10==1:
        print("Epoch number: {} and the loss : {}".format(i,loss.item()))
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

Epoch number: 1 and the loss : 34328.66015625
Epoch number: 11 and the loss : 34355.61328125
Epoch number: 21 and the loss : 36025.62109375
Epoch number: 31 and the loss : 35257.1328125
Epoch number: 41 and the loss : 33742.0546875
Epoch number: 51 and the loss : 34964.05078125
Epoch number: 61 and the loss : 35146.73046875
Epoch number: 71 and the loss : 33501.05078125
Epoch number: 81 and the loss : 35852.77734375
Epoch number: 91 and the loss : 35827.5625
Epoch number: 101 and the loss : 35341.2578125
Epoch number: 111 and the loss : 35029.2421875
Epoch number: 121 and the loss : 36387.01171875
Epoch number: 131 and the loss : 35523.30859375
Epoch number: 141 and the loss : 34857.22265625
Epoch number: 151 and the loss : 36218.39453125
Epoch number: 161 and the loss : 34842.39453125
Epoch number: 171 and the loss : 36076.34765625
Epoch number: 181 and the loss : 35437.78515625
Epoch number: 191 and the loss : 35347.546875
Epoch number: 201 and the loss : 35053.16015625
Epoch number: 211 and the loss : 34241.578125
Epoch number: 221 and the loss : 36146.421875
Epoch number: 231 and the loss : 34326.09765625
Epoch number: 241 and the loss : 33144.41015625
Epoch number: 251 and the loss : 34039.953125
Epoch number: 261 and the loss : 34347.46484375
Epoch number: 271 and the loss : 35772.40234375
Epoch number: 281 and the loss : 34341.37890625
Epoch number: 291 and the loss : 33981.0703125
Epoch number: 301 and the loss : 34525.34375
Epoch number: 311 and the loss : 34465.37109375
Epoch number: 321 and the loss : 33525.42578125
Epoch number: 331 and the loss : 34000.24609375
Epoch number: 341 and the loss : 35009.140625
Epoch number: 351 and the loss : 36175.37890625
Epoch number: 361 and the loss : 34359.13671875
Epoch number: 371 and the loss : 34799.90234375
Epoch number: 381 and the loss : 35214.7109375
Epoch number: 391 and the loss : 36436.46875
Epoch number: 401 and the loss : 35638.59765625
Epoch number: 411 and the loss : 35830.85546875
Epoch number: 421 and the loss : 34071.58203125
Epoch number: 431 and the loss : 34544.75
Epoch number: 441 and the loss : 33456.27734375
Epoch number: 451 and the loss : 33856.1875
Epoch number: 461 and the loss : 33401.19140625
Epoch number: 471 and the loss : 34955.671875
Epoch number: 481 and the loss : 35220.21484375
Epoch number: 491 and the loss : 33801.87890625
Epoch number: 501 and the loss : 34578.5
Epoch number: 511 and the loss : 35334.28515625
Epoch number: 521 and the loss : 36325.26171875
Epoch number: 531 and the loss : 35063.2890625
Epoch number: 541 and the loss : 34485.15234375
Epoch number: 551 and the loss : 35251.21484375
Epoch number: 561 and the loss : 33757.11328125
Epoch number: 571 and the loss : 33362.0078125
Epoch number: 581 and the loss : 34779.875
Epoch number: 591 and the loss : 35132.8359375
Epoch number: 601 and the loss : 33613.55078125
Epoch number: 611 and the loss : 35348.53125
Epoch number: 621 and the loss : 32927.77734375
Epoch number: 631 and the loss : 35034.046875
Epoch number: 641 and the loss : 35553.05859375
Epoch number: 651 and the loss : 34620.99609375
Epoch number: 661 and the loss : 34912.3203125
Epoch number: 671 and the loss : 34121.8203125
Epoch number: 681 and the loss : 34576.25
Epoch number: 691 and the loss : 35166.27734375
Epoch number: 701 and the loss : 36380.125
Epoch number: 711 and the loss : 34969.89453125
Epoch number: 721 and the loss : 35005.125
Epoch number: 731 and the loss : 35467.8515625
Epoch number: 741 and the loss : 34151.40234375
Epoch number: 751 and the loss : 35452.1953125
Epoch number: 761 and the loss : 33719.39453125
Epoch number: 771 and the loss : 36136.90234375
Epoch number: 781 and the loss : 34310.55078125
Epoch number: 791 and the loss : 35170.94921875
Epoch number: 801 and the loss : 35488.75390625
Epoch number: 811 and the loss : 34272.2890625
Epoch number: 821 and the loss : 33238.4296875
Epoch number: 831 and the loss : 33786.7578125
Epoch number: 841 and the loss : 34982.86328125
Epoch number: 851 and the loss : 36397.73046875
Epoch number: 861 and the loss : 35224.56640625
Epoch number: 871 and the loss : 34388.7265625
Epoch number: 881 and the loss : 35628.08984375
Epoch number: 891 and the loss : 33448.1171875
Epoch number: 901 and the loss : 34824.3515625
Epoch number: 911 and the loss : 35251.69140625
Epoch number: 921 and the loss : 35366.42578125
Epoch number: 931 and the loss : 33498.49609375
Epoch number: 941 and the loss : 36319.21875
Epoch number: 951 and the loss : 33441.5703125
Epoch number: 961 and the loss : 34964.234375
Epoch number: 971 and the loss : 33854.9375
Epoch number: 981 and the loss : 37294.3828125
Epoch number: 991 and the loss : 33516.4375
Epoch number: 1001 and the loss : 34400.33984375
Epoch number: 1011 and the loss : 33861.27734375
Epoch number: 1021 and the loss : 36946.4765625
Epoch number: 1031 and the loss : 34895.875
Epoch number: 1041 and the loss : 34803.26171875
Epoch number: 1051 and the loss : 35439.04296875
Epoch number: 1061 and the loss : 34524.94140625
Epoch number: 1071 and the loss : 34580.14453125
Epoch number: 1081 and the loss : 35005.921875
Epoch number: 1091 and the loss : 37550.62890625
Epoch number: 1101 and the loss : 34967.57421875
Epoch number: 1111 and the loss : 34419.52734375
Epoch number: 1121 and the loss : 35754.671875
Epoch number: 1131 and the loss : 35236.08984375
Epoch number: 1141 and the loss : 35632.65234375
Epoch number: 1151 and the loss : 34614.03125
Epoch number: 1161 and the loss : 34914.953125
Epoch number: 1171 and the loss : 33536.8515625
Epoch number: 1181 and the loss : 34582.453125
Epoch number: 1191 and the loss : 34963.48046875
Epoch number: 1201 and the loss : 36169.62109375
Epoch number: 1211 and the loss : 35308.30078125
Epoch number: 1221 and the loss : 34848.98828125
Epoch number: 1231 and the loss : 33660.51953125
Epoch number: 1241 and the loss : 35108.16015625
Epoch number: 1251 and the loss : 35924.33984375
Epoch number: 1261 and the loss : 33410.40234375
Epoch number: 1271 and the loss : 33509.61328125
Epoch number: 1281 and the loss : 35051.6171875
Epoch number: 1291 and the loss : 34763.56640625
Epoch number: 1301 and the loss : 34419.12109375
Epoch number: 1311 and the loss : 34632.09765625
Epoch number: 1321 and the loss : 35145.7890625
Epoch number: 1331 and the loss : 34902.05859375
Epoch number: 1341 and the loss : 33314.1328125
Epoch number: 1351 and the loss : 33246.890625
Epoch number: 1361 and the loss : 42318.46484375
Epoch number: 1371 and the loss : 32277.2109375
Epoch number: 1381 and the loss : 33904.80078125
Epoch number: 1391 and the loss : 36038.3046875
Epoch number: 1401 and the loss : 37252.171875
Epoch number: 1411 and the loss : 35943.8046875
Epoch number: 1421 and the loss : 34247.109375
Epoch number: 1431 and the loss : 33291.9453125
Epoch number: 1441 and the loss : 34566.34765625
Epoch number: 1451 and the loss : 32626.41015625
Epoch number: 1461 and the loss : 35237.1953125
Epoch number: 1471 and the loss : 35355.46484375
Epoch number: 1481 and the loss : 35080.21875
Epoch number: 1491 and the loss : 34694.9375
Epoch number: 1501 and the loss : 34006.02734375
Epoch number: 1511 and the loss : 34648.76171875
Epoch number: 1521 and the loss : 37352.42578125
Epoch number: 1531 and the loss : 33877.8046875
Epoch number: 1541 and the loss : 35061.12890625
Epoch number: 1551 and the loss : 34519.76171875
Epoch number: 1561 and the loss : 33805.70703125
Epoch number: 1571 and the loss : 34579.34375
Epoch number: 1581 and the loss : 34273.4453125
Epoch number: 1591 and the loss : 33814.24609375
Epoch number: 1601 and the loss : 33202.2890625
Epoch number: 1611 and the loss : 34764.62890625
Epoch number: 1621 and the loss : 34684.25390625
Epoch number: 1631 and the loss : 33936.05078125
Epoch number: 1641 and the loss : 35014.3984375
Epoch number: 1651 and the loss : 33833.44921875
Epoch number: 1661 and the loss : 34842.375
Epoch number: 1671 and the loss : 34533.234375
Epoch number: 1681 and the loss : 34883.02734375
Epoch number: 1691 and the loss : 34049.69140625
Epoch number: 1701 and the loss : 35746.328125
Epoch number: 1711 and the loss : 33644.95703125
Epoch number: 1721 and the loss : 35353.00390625
Epoch number: 1731 and the loss : 33637.13671875
Epoch number: 1741 and the loss : 34957.921875
Epoch number: 1751 and the loss : 34119.0234375
Epoch number: 1761 and the loss : 34179.0
Epoch number: 1771 and the loss : 34481.17578125
Epoch number: 1781 and the loss : 34004.41015625
Epoch number: 1791 and the loss : 33023.0078125
Epoch number: 1801 and the loss : 35022.01171875
Epoch number: 1811 and the loss : 34045.515625
Epoch number: 1821 and the loss : 34939.21484375
Epoch number: 1831 and the loss : 34672.98046875
Epoch number: 1841 and the loss : 34397.79296875
Epoch number: 1851 and the loss : 33896.40234375
Epoch number: 1861 and the loss : 38604.19921875
Epoch number: 1871 and the loss : 33472.01953125
Epoch number: 1881 and the loss : 34716.0390625
Epoch number: 1891 and the loss : 34085.0078125
Epoch number: 1901 and the loss : 34164.4296875
Epoch number: 1911 and the loss : 34990.61328125
Epoch number: 1921 and the loss : 37885.1484375
Epoch number: 1931 and the loss : 34775.49609375
Epoch number: 1941 and the loss : 34768.640625
Epoch number: 1951 and the loss : 34155.26171875
Epoch number: 1961 and the loss : 34877.0546875
Epoch number: 1971 and the loss : 34802.16015625
Epoch number: 1981 and the loss : 34358.1328125
Epoch number: 1991 and the loss : 35376.58203125
Epoch number: 2001 and the loss : 33571.796875
Epoch number: 2011 and the loss : 33978.73046875
Epoch number: 2021 and the loss : 35266.96484375
Epoch number: 2031 and the loss : 36044.58203125
Epoch number: 2041 and the loss : 34903.3515625
Epoch number: 2051 and the loss : 34112.4296875
Epoch number: 2061 and the loss : 33797.05859375
Epoch number: 2071 and the loss : 34538.0390625
Epoch number: 2081 and the loss : 35262.9609375
Epoch number: 2091 and the loss : 33749.3359375
Epoch number: 2101 and the loss : 34417.453125
Epoch number: 2111 and the loss : 34341.4609375
Epoch number: 2121 and the loss : 33874.046875
Epoch number: 2131 and the loss : 34261.33203125
Epoch number: 2141 and the loss : 34909.4453125
Epoch number: 2151 and the loss : 34166.9140625
Epoch number: 2161 and the loss : 35149.67578125
Epoch number: 2171 and the loss : 34395.453125
Epoch number: 2181 and the loss : 34651.65625
Epoch number: 2191 and the loss : 35846.9765625
Epoch number: 2201 and the loss : 34070.59375
Epoch number: 2211 and the loss : 34578.61328125
Epoch number: 2221 and the loss : 34278.65234375
Epoch number: 2231 and the loss : 35077.82421875
Epoch number: 2241 and the loss : 34407.375
Epoch number: 2251 and the loss : 35360.1015625
Epoch number: 2261 and the loss : 33198.70703125
Epoch number: 2271 and the loss : 33176.4921875
Epoch number: 2281 and the loss : 35080.75390625
Epoch number: 2291 and the loss : 34805.62890625
Epoch number: 2301 and the loss : 33382.9140625
Epoch number: 2311 and the loss : 34029.48046875
Epoch number: 2321 and the loss : 34493.9453125
Epoch number: 2331 and the loss : 34017.421875
Epoch number: 2341 and the loss : 35443.70703125
Epoch number: 2351 and the loss : 33891.7734375
Epoch number: 2361 and the loss : 33972.81640625
Epoch number: 2371 and the loss : 34538.8984375
Epoch number: 2381 and the loss : 35203.76171875
Epoch number: 2391 and the loss : 35187.24609375
Epoch number: 2401 and the loss : 35075.0
Epoch number: 2411 and the loss : 33880.08984375
Epoch number: 2421 and the loss : 34045.79296875
Epoch number: 2431 and the loss : 33927.4375
Epoch number: 2441 and the loss : 33537.3359375
Epoch number: 2451 and the loss : 35625.83984375
Epoch number: 2461 and the loss : 35152.8203125
Epoch number: 2471 and the loss : 34281.796875
Epoch number: 2481 and the loss : 34488.0703125
Epoch number: 2491 and the loss : 33964.2578125
Epoch number: 2501 and the loss : 32480.3359375
Epoch number: 2511 and the loss : 34211.94921875
Epoch number: 2521 and the loss : 34378.8359375
Epoch number: 2531 and the loss : 32906.1796875
Epoch number: 2541 and the loss : 35712.08984375
Epoch number: 2551 and the loss : 34696.2890625
Epoch number: 2561 and the loss : 33912.16796875
Epoch number: 2571 and the loss : 34557.02734375
Epoch number: 2581 and the loss : 33599.4296875
Epoch number: 2591 and the loss : 34856.86328125
Epoch number: 2601 and the loss : 35000.83984375
Epoch number: 2611 and the loss : 34089.8359375
Epoch number: 2621 and the loss : 33132.84375
Epoch number: 2631 and the loss : 32305.076171875
Epoch number: 2641 and the loss : 33683.5
Epoch number: 2651 and the loss : 33341.06640625
Epoch number: 2661 and the loss : 34434.078125
Epoch number: 2671 and the loss : 34056.6875
Epoch number: 2681 and the loss : 32585.27734375
Epoch number: 2691 and the loss : 38258.6328125
Epoch number: 2701 and the loss : 35244.51171875
Epoch number: 2711 and the loss : 33177.33203125
Epoch number: 2721 and the loss : 35250.59375
Epoch number: 2731 and the loss : 33690.7578125
Epoch number: 2741 and the loss : 34046.30859375
Epoch number: 2751 and the loss : 36266.6875
Epoch number: 2761 and the loss : 33586.6796875
Epoch number: 2771 and the loss : 35483.6796875
Epoch number: 2781 and the loss : 34372.08984375
Epoch number: 2791 and the loss : 33560.65625
Epoch number: 2801 and the loss : 35436.3515625
Epoch number: 2811 and the loss : 34802.67578125
Epoch number: 2821 and the loss : 35003.2421875
Epoch number: 2831 and the loss : 37144.890625
Epoch number: 2841 and the loss : 35052.32421875
Epoch number: 2851 and the loss : 35154.35546875
Epoch number: 2861 and the loss : 32686.91796875
Epoch number: 2871 and the loss : 35082.15234375
Epoch number: 2881 and the loss : 33492.9453125
Epoch number: 2891 and the loss : 35063.62890625
Epoch number: 2901 and the loss : 35118.0625
Epoch number: 2911 and the loss : 35192.8125
Epoch number: 2921 and the loss : 34367.0859375
Epoch number: 2931 and the loss : 34447.7421875
Epoch number: 2941 and the loss : 32730.810546875
Epoch number: 2951 and the loss : 35581.94140625
Epoch number: 2961 and the loss : 34581.078125
Epoch number: 2971 and the loss : 34249.8828125
Epoch number: 2981 and the loss : 32838.6796875
Epoch number: 2991 and the loss : 36008.94921875
Epoch number: 3001 and the loss : 35606.4765625
Epoch number: 3011 and the loss : 33533.84765625
Epoch number: 3021 and the loss : 35017.63671875
Epoch number: 3031 and the loss : 33608.15234375
Epoch number: 3041 and the loss : 33071.92578125
Epoch number: 3051 and the loss : 33019.28125
Epoch number: 3061 and the loss : 34729.953125
Epoch number: 3071 and the loss : 34506.77734375
Epoch number: 3081 and the loss : 34832.51171875
Epoch number: 3091 and the loss : 35133.2890625
Epoch number: 3101 and the loss : 33282.42578125
Epoch number: 3111 and the loss : 34237.71484375
Epoch number: 3121 and the loss : 33423.28515625
Epoch number: 3131 and the loss : 35437.4609375
Epoch number: 3141 and the loss : 34462.2109375
Epoch number: 3151 and the loss : 34162.5703125
Epoch number: 3161 and the loss : 33038.61328125
Epoch number: 3171 and the loss : 35096.05859375
Epoch number: 3181 and the loss : 34242.5234375
Epoch number: 3191 and the loss : 36002.09375
Epoch number: 3201 and the loss : 35424.86328125
Epoch number: 3211 and the loss : 34192.27734375
Epoch number: 3221 and the loss : 33531.28515625
Epoch number: 3231 and the loss : 33592.86328125
Epoch number: 3241 and the loss : 34813.03515625
Epoch number: 3251 and the loss : 34519.578125
Epoch number: 3261 and the loss : 32932.3671875
Epoch number: 3271 and the loss : 33858.8515625
Epoch number: 3281 and the loss : 35942.4609375
Epoch number: 3291 and the loss : 34941.66015625
Epoch number: 3301 and the loss : 34997.140625
Epoch number: 3311 and the loss : 34961.578125
Epoch number: 3321 and the loss : 34584.58984375
Epoch number: 3331 and the loss : 34136.4765625
Epoch number: 3341 and the loss : 34645.15625
Epoch number: 3351 and the loss : 34153.3046875
Epoch number: 3361 and the loss : 34144.44140625
Epoch number: 3371 and the loss : 32646.822265625
Epoch number: 3381 and the loss : 34906.36328125
Epoch number: 3391 and the loss : 34112.640625
Epoch number: 3401 and the loss : 34533.98046875
Epoch number: 3411 and the loss : 34116.51171875
Epoch number: 3421 and the loss : 35539.36328125
Epoch number: 3431 and the loss : 33883.015625
Epoch number: 3441 and the loss : 35749.26171875
Epoch number: 3451 and the loss : 34057.00390625
Epoch number: 3461 and the loss : 35320.13671875
Epoch number: 3471 and the loss : 34141.8984375
Epoch number: 3481 and the loss : 34281.42578125
Epoch number: 3491 and the loss : 33356.640625
Epoch number: 3501 and the loss : 33610.67578125
Epoch number: 3511 and the loss : 35509.25
Epoch number: 3521 and the loss : 34516.18359375
Epoch number: 3531 and the loss : 33690.3046875
Epoch number: 3541 and the loss : 35234.0703125
Epoch number: 3551 and the loss : 35783.8671875
Epoch number: 3561 and the loss : 34127.4921875
Epoch number: 3571 and the loss : 34307.20703125
Epoch number: 3581 and the loss : 36475.25
Epoch number: 3591 and the loss : 33178.77734375
Epoch number: 3601 and the loss : 33377.203125
Epoch number: 3611 and the loss : 34353.58203125
Epoch number: 3621 and the loss : 33580.62109375
Epoch number: 3631 and the loss : 34168.6953125
Epoch number: 3641 and the loss : 35660.6953125
Epoch number: 3651 and the loss : 35447.5
Epoch number: 3661 and the loss : 34952.359375
Epoch number: 3671 and the loss : 34360.04296875
Epoch number: 3681 and the loss : 34483.453125
Epoch number: 3691 and the loss : 34865.6953125
Epoch number: 3701 and the loss : 34170.9453125
Epoch number: 3711 and the loss : 34715.39453125
Epoch number: 3721 and the loss : 34251.80859375
Epoch number: 3731 and the loss : 36390.79296875
Epoch number: 3741 and the loss : 33569.65625
Epoch number: 3751 and the loss : 33739.33203125
Epoch number: 3761 and the loss : 33496.25390625
Epoch number: 3771 and the loss : 34951.5234375
Epoch number: 3781 and the loss : 32285.580078125
Epoch number: 3791 and the loss : 34238.11328125
Epoch number: 3801 and the loss : 33976.375
Epoch number: 3811 and the loss : 34055.3359375
Epoch number: 3821 and the loss : 33296.8984375
Epoch number: 3831 and the loss : 32676.5
Epoch number: 3841 and the loss : 36006.09765625
Epoch number: 3851 and the loss : 34351.00390625
Epoch number: 3861 and the loss : 34606.0625
Epoch number: 3871 and the loss : 33762.08203125
Epoch number: 3881 and the loss : 35753.8671875
Epoch number: 3891 and the loss : 34055.9921875
Epoch number: 3901 and the loss : 35508.4921875
Epoch number: 3911 and the loss : 33663.7109375
Epoch number: 3921 and the loss : 35361.33203125
Epoch number: 3931 and the loss : 34105.69140625
Epoch number: 3941 and the loss : 33976.57421875
Epoch number: 3951 and the loss : 33912.19140625
Epoch number: 3961 and the loss : 35564.3671875
Epoch number: 3971 and the loss : 33347.25390625
Epoch number: 3981 and the loss : 34506.16015625
Epoch number: 3991 and the loss : 34878.44921875
Epoch number: 4001 and the loss : 32929.6484375
Epoch number: 4011 and the loss : 36799.31640625
Epoch number: 4021 and the loss : 34679.91015625
Epoch number: 4031 and the loss : 35239.41796875
Epoch number: 4041 and the loss : 35531.44921875
Epoch number: 4051 and the loss : 34783.1015625
Epoch number: 4061 and the loss : 34902.0390625
Epoch number: 4071 and the loss : 34496.4140625
Epoch number: 4081 and the loss : 33439.14453125
Epoch number: 4091 and the loss : 34877.10546875
Epoch number: 4101 and the loss : 32234.490234375
Epoch number: 4111 and the loss : 33443.75
Epoch number: 4121 and the loss : 32855.984375
Epoch number: 4131 and the loss : 35648.75
Epoch number: 4141 and the loss : 34383.54296875
Epoch number: 4151 and the loss : 34823.15625
Epoch number: 4161 and the loss : 33929.2578125
Epoch number: 4171 and the loss : 35184.88671875

In [177]:
#### Validate the Test Data
y_pred=""
with torch.no_grad():
    y_pred=model(test_categorical,test_cont)
    loss=torch.sqrt(loss_function(y_pred,y_test))
print('RMSE: {}'.format(loss))

RMSE: 45899.5625

In [179]:
data_verify=pd.DataFrame(y_test.tolist(),columns=["Test"])

In [181]:
data_predicted=pd.DataFrame(y_pred.tolist(),columns=["Prediction"])

In [184]:
data_predicted

        Prediction
0    157620.859375
1    109154.914062
2    171355.703125
3    220284.359375
4    193250.671875
5    211570.546875
6    203497.093750
7    302878.625000
8    148640.593750
9    362125.906250
10   251606.234375
11   205394.796875
12   234192.859375
13   112551.851562
14   268338.156250
15   128826.835938
16   209843.484375
17   141096.296875
18   289030.437500
19    78536.703125
20   189581.671875
21   121491.367188
22   117318.554688
23   193231.671875
24   160906.406250
25   163867.750000
26   151816.437500
27   452136.156250
28   153394.687500
29   121840.765625
30    97033.039062
31   121595.585938
32   232132.203125
33   132157.171875
34   218714.484375
35   173551.359375
36   148905.375000
37   100665.812500
38   192867.234375
39   102220.843750
40   229617.453125
41   289295.750000
42   111506.195312
43   224857.953125
44   176836.062500
45   121376.101562
46   120955.843750
47   113592.875000
48   120923.984375
49   324658.937500
50   133605.609375
51   248856.578125
52   221802.640625
53   137802.296875
54   252018.640625
55   208662.046875
56   144426.265625
57   128816.218750
58   219201.671875
59   200998.078125
60   274353.937500
61   118771.851562
62   208730.765625
63   260582.328125
64   177186.250000
65   122858.015625
66   140886.031250
67   258370.500000
68    67132.773438
69   316140.562500
70    72691.773438
71    91475.382812
72    97356.781250
73   183339.968750
74   219886.734375
75   238720.562500
76   151008.187500
77    96162.570312
78    99591.859375
79   106710.593750
80   171526.265625
81   135604.640625
82    93670.554688
83   230997.046875
84   127371.078125
85   115989.648438
86   159657.671875
87   153841.906250
88   159192.484375
89   100344.812500
90   291342.625000
91   156799.859375
92   147697.796875
93   185375.921875
94    97216.492188
95   337164.406250
96   191048.000000
97   247120.921875
98   368088.781250
99   210587.125000
100  209047.359375
101  131358.703125
102  179928.296875
103  117150.109375
104  302470.906250
105  135951.468750
106  193788.781250
107  253051.828125
108  192643.171875
109  231174.312500
110   77693.968750
111  147540.984375
112   73474.679688
113  186025.234375
114   80759.851562
115  198433.593750
116   91022.929688
117   84663.500000
118  334955.250000
119  126609.039062
120  306544.687500
121   99363.085938
122  186767.734375
123  122635.906250
124  106793.851562
125  106123.117188
126  185799.765625
127  343462.750000
128  100578.507812
129  158455.968750
130  139582.140625
131   95143.789062
132  211064.765625
133  170624.234375
134  242908.062500
135  104321.843750
136  180059.765625
137   98651.304688
138  118743.281250
139  314963.343750
140  234008.015625
141  168685.203125
142  117717.101562
143  337494.437500
144  159506.031250
145  184590.703125
146   91918.882812
147  145802.640625
148  154397.921875
149  121991.398438
150  122003.304688
151  156288.437500
152  282024.468750
153  145657.578125
154   86833.960938
155  251594.187500
156  121866.539062
157  200567.265625
158  152986.687500
159  163817.515625
160  103615.937500
161  277887.562500
162  107888.960938
163  220308.796875
164  220093.109375
165  279361.062500
166  189921.421875
167  143904.453125
168  237058.296875
169  104144.953125
170   57272.988281
171  125529.007812
172  261687.015625
173  125735.632812
174  215406.937500
175  210820.484375
176  206406.203125
177  316896.187500
178  251108.328125
179  103088.921875

In [187]:
final_output=pd.concat([data_verify,data_predicted],axis=1)
final_output['Difference']=final_output['Test']-final_output['Prediction']
final_output.head()

       Test     Prediction    Difference
0  130000.0  157620.859375 -27620.859375
1  138887.0  109154.914062  29732.085938
2  175500.0  171355.703125   4144.296875
3  195000.0  220284.359375 -25284.359375
4  142500.0  193250.671875 -50750.671875

In [189]:
#### Saving The Model
#### Save the model
torch.save(model,'HousePrice.pt')

In [191]:
torch.save(model.state_dict(),'HouseWeights.pt')

In [193]:
### Loading the saved Model
embs_size=[(15, 8), (5, 3), (2, 1), (4, 2)]
model1=FeedForwardNN(embs_size,5,1,[100,50],p=0.4)

In [194]:
model1.load_state_dict(torch.load('HouseWeights.pt'))

C:\Users\TEJ SAI PRANAV REDDY\AppData\Local\Temp\ipykernel_21960\2229105223.py:1: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model1.load_state_dict(torch.load('HouseWeights.pt'))

In [196]:
model1.eval()

FeedForwardNN(
  (embeds): ModuleList(
    (0): Embedding(15, 8)
    (1): Embedding(5, 3)
    (2): Embedding(2, 1)
    (3): Embedding(4, 2)
  )
  (emb_drop): Dropout(p=0.4, inplace=False)
  (bn_cont): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (layers): Sequential(
    (0): Linear(in_features=19, out_features=100, bias=True)
    (1): ReLU(inplace=True)
    (2): BatchNorm1d(100, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (3): Dropout(p=0.4, inplace=False)
    (4): Linear(in_features=100, out_features=50, bias=True)
    (5): ReLU(inplace=True)
    (6): BatchNorm1d(50, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (7): Dropout(p=0.4, inplace=False)
    (8): Linear(in_features=50, out_features=1, bias=True)
  )
)